name: outputs_test

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.test }}
      outpus2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run: echo "test=Hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=World" >> $GITHUB_OUTPUT

    